const int
SPELL_EXPLOSIVE_RUNES = 806,
SPELL_DANCING_LIGHTS = 807,
SPELL_SEPIA_SNAKE_SIGIL = 809,

POLYMORPH_TYPE_RAVEN = 115,
POLYMORPH_TYPE_BAT = 116,
POLYMORPH_TYPE_GOBLINSHAMAN = 117,

POLYMORPH_TYPE_BOY = 80,
POLYMORPH_TYPE_GIRL = 81,

POLYMORPH_TYPE_RAKSHASA_MALE = 88,
POLYMORPH_TYPE_RAKSHASA_FEMALE = 89,

POLYMORPH_TYPE_FALCON = 120,
POLYMORPH_TYPE_WINTERWOLF = 102,

POLYMORPH_TYPE_HUMAN_MALE_15 = 122,
POLYMORPH_TYPE_HUMAN_FEMALE_04 = 123,

POLYMORPH_TYPE_FOX = 121,

POLYMORPH_TYPE_NYMPH = 124,

POLYMORPH_TYPE_VIPER_MED_FOREST = 125,
POLYMORPH_TYPE_VIPER_MED_SWAMP = 126,
POLYMORPH_TYPE_VIPER_MED_JUNGLE = 127,
POLYMORPH_TYPE_VIPER_MED_DESERT = 128,
POLYMORPH_TYPE_VIPER_TINY_FOREST = 129,
POLYMORPH_TYPE_VIPER_TINY_SWAMP = 130,
POLYMORPH_TYPE_VIPER_TINY_JUNGLE = 131,
POLYMORPH_TYPE_VIPER_TINY_DESERT = 132,

POLYMORPH_TYPE_PROSTITUTE_1 = 133,
POLYMORPH_TYPE_PROSTITUTE_2 = 134,

POLYMORPH_TYPE_HORSE_BAY = 135,

POLYMORPH_TYPE_HALFLING_MALE = 136,
POLYMORPH_TYPE_HALFLING_FEMALE = 137,

POLYMORPH_TYPE_FAERIEDRAGON = 138,

POLYMORPH_TYPE_GIANTEAGLE = 139,


VFX_DUR_AFK = 659,


VFX_DUR_FW_FOUNTAIN_SPARK = 584,
VFX_DUR_FW_FOUNTAIN_RED_SPARK = 585,
VFX_DUR_FW_FOUNTAIN_BLUE_SPARK = 586,
VFX_FNF_FW_BLAST_S_BLUE = 587,
VFX_FNF_FW_BLAST_B_BLUE = 588,
VFX_FNF_FW_BLAST_S_RED = 589,
VFX_FNF_FW_BLAST_B_RED = 590,
VFX_FNF_FW_BLAST_S_YELLOW = 591,
VFX_FNF_FW_BLAST_B_YELLOW = 592,
VFX_FNF_FW_BLAST_S_WHITE = 593,
VFX_FNF_FW_BLAST_B_WHITE = 594,
VFX_FNF_FW_BLAST_S_ORANGE = 595,
VFX_FNF_FW_BLAST_B_ORANGE = 596,
VFX_FNF_FW_BLAST_S_GREEN = 597,
VFX_FNF_FW_BLAST_B_GREEN = 598,
VFX_FNF_FW_BLAST_S_PURPLE = 599,
VFX_FNF_FW_BLAST_B_PURPLE = 600,
VFX_FNF_FW_FLAME_NORMAL = 601,
VFX_FNF_FW_FLAME_GREEN = 602,
VFX_FNF_FW_FLAME_BLUE = 603,
VFX_FNF_FW_FLAME_PURPLE = 604,
VFX_FNF_FW_BLUR_NORMAL = 605,
VFX_FNF_FW_BLUR_YELLOW = 606,
VFX_FNF_FW_BLUR_WHITE = 607,
VFX_FNF_FW_BLUR_BLUE = 608,
VFX_FNF_FW_BLUR_RED = 609,
VFX_FNF_FW_BLUR_ORANGE = 610,
VFX_FNF_FW_BLUR_GREEN = 611,
VFX_FNF_FW_BLUR_PURPLE = 612,
VFX_FNF_FW_STARRY_S_BLUE = 613,
VFX_FNF_FW_STARRY_B_BLUE = 614,
VFX_FNF_FW_STARRY_S_RED = 615,
VFX_FNF_FW_STARRY_B_RED = 616,
VFX_FNF_FW_STARRY_S_YELLOW = 617,
VFX_FNF_FW_STARRY_B_YELLOW = 618,
VFX_FNF_FW_STARRY_S_WHITE = 619,
VFX_FNF_FW_STARRY_B_WHITE = 620,
VFX_FNF_FW_STARRY_S_ORANGE = 621,
VFX_FNF_FW_STARRY_B_ORANGE = 622,
VFX_FNF_FW_STARRY_S_GREEN = 623,
VFX_FNF_FW_STARRY_B_GREEN = 624,
VFX_FNF_FW_STARRY_S_PURPLE = 625,
VFX_FNF_FW_STARRY_B_PURPLE = 626,
VFX_FNF_FW_SPECIAL_WRAITH = 627,
VFX_FNF_FW_SPECIAL_SPIRAL = 628,
VFX_FNF_FW_SPECIAL_FAIRY = 629,
VFX_FNF_FW_SPIRAL_S_FIRE = 630,
VFX_FNF_FW_SPIRAL_D_FIRE = 631,
VFX_FNF_FW_SPIRAL_S_BLUE = 632,
VFX_FNF_FW_SPIRAL_D_BLUE = 633,
VFX_FNF_FW_SPIRAL_S_RED = 634,
VFX_FNF_FW_SPIRAL_D_RED = 635,
VFX_FNF_FW_SPIRAL_S_WHITE = 636,
VFX_FNF_FW_SPIRAL_D_WHITE = 637,
VFX_FNF_FW_SPIRAL_S_GREEN = 638,
VFX_FNF_FW_SPIRAL_D_GREEN = 639,
VFX_FNF_FW_SPIRAL_S_PURPLE = 640,
VFX_FNF_FW_SPIRAL_D_PURPLE = 641,
VFX_DUR_VORTEX = 642,
VFX_DUR_VORTEXD = 643,
VFX_DUR_VORTEXU = 644,
VFX_DUR_VORTEXV = 645,
VFX_DUR_DAGGERS = 646,
VFX_DUR_BLINDDEAF = 647,
VFX_DUR_FLYINGLEAF = 648,
VFX_DUR_GLOBE = 649,
VFX_DUR_PAPILLIONS = 650,
VFX_DUR_DEATH_WARD = 651,
VFX_DUR_SUMMON3 = 652,
VFX_DUR_TIME = 653,
VFX_DUR_WIGGLES = 654,
VFX_FNF_SILENTQUEEN = 655,
VFX_IMP_PROT_KOSSUTH = 656,
VFX_IMP_PROT_OGHMA = 657,
VFX_DUR_STRANGE_SPIRIT = 658,

INVALID_INT = -1;

/*
 * 584   VFX_DUR_FW_FOUNTAIN_SPARK
 * 585   VFX_DUR_FW_FOUNTAIN_RED_SPARK
 * 586   VFX_DUR_FW_FOUNTAIN_BLUE_SPARK
 * 587   VFX_FNF_FW_BLAST_S_BLUE
 * 588   VFX_FNF_FW_BLAST_B_BLUE
 * 589   VFX_FNF_FW_BLAST_S_RED
 * 590   VFX_FNF_FW_BLAST_B_RED
 * 591   VFX_FNF_FW_BLAST_S_YELLOW
 * 592   VFX_FNF_FW_BLAST_B_YELLOW
 * 593   VFX_FNF_FW_BLAST_S_WHITE
 * 594   VFX_FNF_FW_BLAST_B_WHITE
 * 595   VFX_FNF_FW_BLAST_S_ORANGE
 * 596   VFX_FNF_FW_BLAST_B_ORANGE
 * 597   VFX_FNF_FW_BLAST_S_GREEN
 * 598   VFX_FNF_FW_BLAST_B_GREEN
 * 599   VFX_FNF_FW_BLAST_S_PURPLE
 * 600   VFX_FNF_FW_BLAST_B_PURPLE
 * 601   VFX_FNF_FW_FLAME_NORMAL
 * 602   VFX_FNF_FW_FLAME_GREEN
 * 603   VFX_FNF_FW_FLAME_BLUE
 * 604   VFX_FNF_FW_FLAME_PURPLE
 * 605   VFX_FNF_FW_BLUR_NORMAL
 * 606   VFX_FNF_FW_BLUR_YELLOW
 * 607   VFX_FNF_FW_BLUR_WHITE
 * 608   VFX_FNF_FW_BLUR_BLUE
 * 609   VFX_FNF_FW_BLUR_RED
 * 610   VFX_FNF_FW_BLUR_ORANGE
 * 611   VFX_FNF_FW_BLUR_GREEN
 * 612   VFX_FNF_FW_BLUR_PURPLE
 * 613   VFX_FNF_FW_STARRY_S_BLUE
 * 614   VFX_FNF_FW_STARRY_B_BLUE
 * 615   VFX_FNF_FW_STARRY_S_RED
 * 616   VFX_FNF_FW_STARRY_B_RED
 * 617   VFX_FNF_FW_STARRY_S_YELLOW
 * 618   VFX_FNF_FW_STARRY_B_YELLOW
 * 619   VFX_FNF_FW_STARRY_S_WHITE
 * 620   VFX_FNF_FW_STARRY_B_WHITE
 * 621   VFX_FNF_FW_STARRY_S_ORANGE
 * 622   VFX_FNF_FW_STARRY_B_ORANGE
 * 623   VFX_FNF_FW_STARRY_S_GREEN
 * 624   VFX_FNF_FW_STARRY_B_GREEN
 * 625   VFX_FNF_FW_STARRY_S_PURPLE
 * 626   VFX_FNF_FW_STARRY_B_PURPLE
 * 627   VFX_FNF_FW_SPECIAL_WRAITH
 * 628   VFX_FNF_FW_SPECIAL_SPIRAL
 * 629   VFX_FNF_FW_SPECIAL_FAIRY
 * 630   VFX_FNF_FW_SPIRAL_S_FIRE
 * 631   VFX_FNF_FW_SPIRAL_D_FIRE
 * 632   VFX_FNF_FW_SPIRAL_S_BLUE
 * 633   VFX_FNF_FW_SPIRAL_D_BLUE
 * 634   VFX_FNF_FW_SPIRAL_S_RED
 * 635   VFX_FNF_FW_SPIRAL_D_RED
 * 636   VFX_FNF_FW_SPIRAL_S_WHITE
 * 637   VFX_FNF_FW_SPIRAL_D_WHITE
 * 638   VFX_FNF_FW_SPIRAL_S_GREEN
 * 639   VFX_FNF_FW_SPIRAL_D_GREEN
 * 640   VFX_FNF_FW_SPIRAL_S_PURPLE
 * 641   VFX_FNF_FW_SPIRAL_D_PURPLE
 * 642   VFX_DUR_VORTEX
 * 643   VFX_DUR_VORTEXD
 * 644   VFX_DUR_VORTEXU
 * 645   VFX_DUR_VORTEXV
 * 646   VFX_DUR_DAGGERS
 * 647   VFX_DUR_BLINDDEAF
 * 648   VFX_DUR_FLYINGLEAF
 * 649   VFX_DUR_GLOBE
 * 650   VFX_DUR_PAPILLIONS
 * 651   VFX_DUR_DEATH_WARD
 * 652   VFX_DUR_SUMMON3
 * 653   VFX_DUR_TIME
 * 654   VFX_DUR_WIGGLES
 * 655   VFX_FNF_SILENTQUEEN
 * 656   VFX_IMP_PROT_KOSSUTH
 * 657   VFX_IMP_PROT_OGHMA
 * 658   VFX_DUR_STRANGE_SPIRIT
 */
