#define SKILL_SLEIGHT_OF_HAND SKILL_PICK_POCKET
#define SKILL_KNOWLEDGE SKILL_LORE
#define SKILL_DIPLOMACY SKILL_PERSUADE
#define SKILL_SENSE_MOTIVE SKILL_CRAFT_ARMOR
#define SKILL_PROFESSION SKILL_CRAFT_TRAP
#define SKILL_CRAFT_WEAPON SKILL_SURVIVAL
#define SKILL_SURVIVAL 26
#define SKILL_TRICKERY 28
#define SKILLS_2DA_MAX_ID 28

#define IPRP_SPELLS_2DA_MAX_ID 568

#define SPELL_EXPLOSIVE_RUNES 806
#define SPELL_DANCING_LIGHTS 807
#define SPELL_SEPIA_SNAKE_SIGIL 809
#define SPELL_ZONE_OF_SILENCE 817
#define SPELL_SILENCE_PERSONAL 819
#define SPELL_SILENCE_AOE 820
#define SPELL_DIMENSION_DOOR 821
#define SPELL_DISLOCATE 822
#define SPELL_GRENADE_MAGIC 823
#define SPELL_GRENADE_BUGPOD 824
#define SPELL_TRAP_THE_SOUL 825
#define SPELL_RELEASE_THE_SOUL 826
#define SPELL_POWER_WORD_BLIND 827
#define SPELL_POWER_WORD_DISROBE 828
#define SPELL_POWER_WORD_TRIP 829
#define SPELL_POWER_WORD_SILENCE 830
#define SPELL_POWER_WORD_DISABLE 831
#define SPELL_OPEN_CLOSE 832
#define SPELL_ANIMAL_MESSENGER 833
#define SPELL_POWER_WORD_SLEEP 834
#define SPELL_EARTHBOUND 835
#define SPELL_WINGBIND 836
#define SPELL_ASPECT_OF_THE_WOLF 837
#define SPELL_LIGHTNING_RING 838
#define SPELL_FAERIE_FIRE 839
#define SPELL_CACOPHONIC_BURST 840
#define SPELL_IRRESISTIBLE_DANCE 841

#define EFFECT_ICON_ALARM 130

#define IP_CONST_SPELLRESISTANCEBONUS_34 12
#define IP_CONST_SPELLRESISTANCEBONUS_36 13
#define IP_CONST_SPELLRESISTANCEBONUS_38 14
#define IP_CONST_SPELLRESISTANCEBONUS_40 15
#define IP_CONST_SPELLRESISTANCEBONUS_42 16
#define IP_CONST_SPELLRESISTANCEBONUS_44 17
#define IP_CONST_SPELLRESISTANCEBONUS_46 18
#define IP_CONST_SPELLRESISTANCEBONUS_48 19
#define IP_CONST_SPELLRESISTANCEBONUS_50 20
#define IP_CONST_SPELLRESISTANCEBONUS_52 21
#define IP_CONST_SPELLRESISTANCEBONUS_54 22
#define IP_CONST_SPELLRESISTANCEBONUS_56 23
#define IP_CONST_SPELLRESISTANCEBONUS_58 24
#define IP_CONST_SPELLRESISTANCEBONUS_60 25
#define IP_CONST_SPELLRESISTANCEBONUS_62 26
#define IP_CONST_SPELLRESISTANCEBONUS_64 27

// BIOWARE spellscript compat fixes:
// taken from disassembled spell script in orignal distro
#define VFX_DUR_MIRROR_IMAGE 9

#define ITEM_PROPERTY_CURSED 89
#define IP_CONST_CURSED_UNDROPPABLE 0
#define IP_CONST_CURSED_UNUNEQUIPPABLE 1

#define ITEM_PROPERTY_NEGATIVE_LEVELS_DIFFERING_ALIGNMENT 90
#define ITEM_PROPERTY_NEGATIVE_LEVELS 91
#define ITEM_PROPERTY_NEGATIVE_LEVELS_DIFFERING_ALIGNGRP 92
#define ITEM_PROPERTY_NEGATIVE_LEVELS_BY_ALIGNGRP 93
#define ITEM_PROPERTY_NEGATIVE_LEVELS_BY_ALIGNMENT 94
#define ITEM_PROPERTY_SELFIDENTIFYING 95
// IP Adjust Max Dex Bonus 96 -- broken
#define ITEM_PROPERTY_WILDSHAPE_MERGE_AC 97

#define ITEM_PROPERTY_DISPELSAVEDC_INCREASE 98
#define ITEM_PROPERTY_DISPELSAVEDC_DECREASE 99

#define POLYMORPH_TYPE_RAVEN 115
#define POLYMORPH_TYPE_BAT 116
#define POLYMORPH_TYPE_GOBLINSHAMAN 117

#define POLYMORPH_TYPE_BOY 80
#define POLYMORPH_TYPE_GIRL 81

#define POLYMORPH_TYPE_RAKSHASA_MALE 88
#define POLYMORPH_TYPE_RAKSHASA_FEMALE 89

#define POLYMORPH_TYPE_FALCON 120
#define POLYMORPH_TYPE_WINTERWOLF 102

#define POLYMORPH_TYPE_HUMAN_MALE_15 122
#define POLYMORPH_TYPE_HUMAN_FEMALE_04 123

#define POLYMORPH_TYPE_FOX 121
#define POLYMORPH_TYPE_NYMPH 124
#define POLYMORPH_TYPE_VIPER_MED_FOREST 125
#define POLYMORPH_TYPE_VIPER_MED_SWAMP 126
#define POLYMORPH_TYPE_VIPER_MED_JUNGLE 127
#define POLYMORPH_TYPE_VIPER_MED_DESERT 128
#define POLYMORPH_TYPE_VIPER_TINY_FOREST 129
#define POLYMORPH_TYPE_VIPER_TINY_SWAMP 130
#define POLYMORPH_TYPE_VIPER_TINY_JUNGLE 131
#define POLYMORPH_TYPE_VIPER_TINY_DESERT 132
#define POLYMORPH_TYPE_PROSTITUTE_1 133
#define POLYMORPH_TYPE_PROSTITUTE_2 134
#define POLYMORPH_TYPE_HORSE_BAY 135
#define POLYMORPH_TYPE_HALFLING_MALE 136
#define POLYMORPH_TYPE_HALFLING_FEMALE 137
#define POLYMORPH_TYPE_FAERIEDRAGON 138
#define POLYMORPH_TYPE_GIANTEAGLE 139
#define POLYMORPH_TYPE_BLACK_CAT 140
#define POLYMORPH_TYPE_WHITE_CAT 141

#define VFX_DUR_AFK 752

#define VFX_DUR_FW_FOUNTAIN_SPARK 677
#define VFX_DUR_FW_FOUNTAIN_RED_SPARK 678
#define VFX_DUR_FW_FOUNTAIN_BLUE_SPARK 679
#define VFX_FNF_FW_BLAST_S_BLUE 680
#define VFX_FNF_FW_BLAST_B_BLUE 681
#define VFX_FNF_FW_BLAST_S_RED 682
#define VFX_FNF_FW_BLAST_B_RED 683
#define VFX_FNF_FW_BLAST_S_YELLOW 684
#define VFX_FNF_FW_BLAST_B_YELLOW 685
#define VFX_FNF_FW_BLAST_S_WHITE 686
#define VFX_FNF_FW_BLAST_B_WHITE 687
#define VFX_FNF_FW_BLAST_S_ORANGE 688
#define VFX_FNF_FW_BLAST_B_ORANGE 689
#define VFX_FNF_FW_BLAST_S_GREEN 690
#define VFX_FNF_FW_BLAST_B_GREEN 691
#define VFX_FNF_FW_BLAST_S_PURPLE 692
#define VFX_FNF_FW_BLAST_B_PURPLE 693
#define VFX_FNF_FW_FLAME_NORMAL 694
#define VFX_FNF_FW_FLAME_GREEN 695
#define VFX_FNF_FW_FLAME_BLUE 696
#define VFX_FNF_FW_FLAME_PURPLE 697
#define VFX_FNF_FW_BLUR_NORMAL 698
#define VFX_FNF_FW_BLUR_YELLOW 699
#define VFX_FNF_FW_BLUR_WHITE 700
#define VFX_FNF_FW_BLUR_BLUE 701
#define VFX_FNF_FW_BLUR_RED 702
#define VFX_FNF_FW_BLUR_ORANGE 703
#define VFX_FNF_FW_BLUR_GREEN 704
#define VFX_FNF_FW_BLUR_PURPLE 705
#define VFX_FNF_FW_STARRY_S_BLUE 706
#define VFX_FNF_FW_STARRY_B_BLUE 707
#define VFX_FNF_FW_STARRY_S_RED 708
#define VFX_FNF_FW_STARRY_B_RED 709
#define VFX_FNF_FW_STARRY_S_YELLOW 710
#define VFX_FNF_FW_STARRY_B_YELLOW 711
#define VFX_FNF_FW_STARRY_S_WHITE 712
#define VFX_FNF_FW_STARRY_B_WHITE 713
#define VFX_FNF_FW_STARRY_S_ORANGE 714
#define VFX_FNF_FW_STARRY_B_ORANGE 715
#define VFX_FNF_FW_STARRY_S_GREEN 716
#define VFX_FNF_FW_STARRY_B_GREEN 717
#define VFX_FNF_FW_STARRY_S_PURPLE 718
#define VFX_FNF_FW_STARRY_B_PURPLE 719
#define VFX_FNF_FW_SPECIAL_WRAITH 720
#define VFX_FNF_FW_SPECIAL_SPIRAL 721
#define VFX_FNF_FW_SPECIAL_FAIRY 722
#define VFX_FNF_FW_SPIRAL_S_FIRE 723
#define VFX_FNF_FW_SPIRAL_D_FIRE 724
#define VFX_FNF_FW_SPIRAL_S_BLUE 725
#define VFX_FNF_FW_SPIRAL_D_BLUE 726
#define VFX_FNF_FW_SPIRAL_S_RED 727
#define VFX_FNF_FW_SPIRAL_D_RED 728
#define VFX_FNF_FW_SPIRAL_S_WHITE 729
#define VFX_FNF_FW_SPIRAL_D_WHITE 730
#define VFX_FNF_FW_SPIRAL_S_GREEN 731
#define VFX_FNF_FW_SPIRAL_D_GREEN 732
#define VFX_FNF_FW_SPIRAL_S_PURPLE 733
#define VFX_FNF_FW_SPIRAL_D_PURPLE 734
#define VFX_DUR_VORTEX 735
#define VFX_DUR_VORTEXD 736
#define VFX_DUR_VORTEXU 737
#define VFX_DUR_VORTEXV 738
#define VFX_DUR_DAGGERS 739
#define VFX_DUR_BLINDDEAF 740
#define VFX_DUR_FLYINGLEAF 741
#define VFX_DUR_GLOBE 742
#define VFX_DUR_PAPILLIONS 743
#define VFX_DUR_DEATH_WARD 744
#define VFX_DUR_SUMMON96 652
#define VFX_DUR_TIME 746
#define VFX_DUR_WIGGLES 747
#define VFX_FNF_SILENTQUEEN 748
#define VFX_IMP_PROT_KOSSUTH 749
#define VFX_IMP_PROT_OGHMA 750
#define VFX_DUR_STRANGE_SPIRIT 751

#define INVALID_INT -1

#define FACTION_PC 0
#define FACTION_HOSTILE 1
#define FACTION_COMMONER 2
#define FACTION_MERCHANT 3
#define FACTION_DEFENDER 4

// Marken-specific
#define FACTION_TIERE 5
#define FACTION_FEUERKRALLE 6
