resources := $(wildcard $(VALIDEXT))

clean-backup::
	-rm *.*~ *.out *.hak

clean:: clean-backup
	-rm *.hak
	
$(TARGET): $(resources)
	PERLLIB=../../build/lib ../../build/erfpack.pl \
		-H -o $@ $(VALIDEXT)

publish: $(TARGET)
	rsync -Pzva --chmod=go+r $(TARGET) silbermarken@miyeritar:rsync/nwn/hak/ &&\
		ssh silbermarken@miyeritar 'cd ~/rsync/nwn && make'
