all: client_2da client_cep2c

.PHONY: client_2da client_cep2c clean

client_2da:
	make -C client_2da all

client_cep2c:
	make -C client_cep2c all

clean:
	make -C client_2da clean
	make -C client_cep2c clean
