# Set as environment var!
# NWNHOME=/home/elven/nwn

resources := $(wildcard $(VALIDEXT))

path:
ifeq  "$(NWNHOME)" ""
	@echo "env var NWNHOME not set."
	exit 1
endif

clean-backup::
	-rm *.*~ *.out *.hak

clean:: clean-backup
	-rm *.hak
	
$(TARGET): $(resources)
	erfpack.pl -H -o $@ $(VALIDEXT)

publish: $(TARGET)
	rsync -Pzva --chmod=go+r $(TARGET) silbermarken@miyeritar:rsync/nwn/hak/ &&\
		ssh silbermarken@miyeritar 'cd ~/rsync/nwn && make'
