resources := $(wildcard $(VALIDEXT))

clean-backup::
	-rm *.*~ *.out *.hak

clean:: clean-backup
	-rm *.hak

$(TARGET): $(resources)
	PERLLIB=../../build/lib ../../build/erfpack.pl \
		-H -o $@ $(VALIDEXT) && \
		ruby -e 'File.open(ARGV.shift,"r+b"){|f| f.seek(32); f.write("\x00" * 8) }' $@
